name: plumduffer
recipe: mean
config:
    node: 20
    port: 3000
    ssl: true
    build: false
    command: false
    database: postgres:14
services:
    appserver:
        build:
            - curl -fsSL https://get.pnpm.io/install.sh | bash -
            - pnpm add -g npm-check-updates
        overrides:
            environment:
                PNPM_HOME: /home/node/.local/share/pnpm
                PATH: /home/node/.local/share/pnpm:$PATH
                NPM_CONFIG_PREFIX:
        scanner: false
        sslExpose: false
tooling:
    pnpm:
        service: appserver
    ncu:
        service: appserver
        description: Runs npm-check-updates global package
proxy:
    appserver:
        - plumduffer.lndo.site:3000
        - cms.plumduffer.lndo.site:3001
